/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wzj_ndkdemos_JNIUtil */

#ifndef _Included_com_wzj_ndkdemos_JNIUtil
#define _Included_com_wzj_ndkdemos_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wzj_ndkdemos_JNIUtil
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wzj_ndkdemos_JNIUtil_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
